soul/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views

from django.conf.urls import url,include
from django.conf.urls.static import static
from django.conf import settings
from accounts.views import *

urlpatterns = [
    path('', LoginView.as_view(),name='login'),
    path('logout/', LogoutView.as_view(),name='logout'),
    path('home/', HomeView.as_view(),name='home'),
    path('admin/', admin.site.urls),
    path('mark_as_read/', MarkAsRead.as_view(),name='mark_as_read'),
    path('accounts/password_change/', PasswordChangeView.as_view(),name='password_change'),

    #password reset paths
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='accounts/forgot_password.html'),name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_sent.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/set_new_password.html'),name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),name='password_reset_complete'),

    #common paths
    path('task/',TaskListView.as_view(),name='task'),
    path('task/<id>/',TaskView.as_view(),name='task_detail'),
    path('task/update/<id>',TaskUpdate.as_view(),name='task_update'),
    path('student_register',StudentRegister.as_view(),name='student_register'),
    path('profile/', ProfileView.as_view(),name='profile'),
    path('profile/update/', ProfileUpdate.as_view(),name='profile_update'),
    path('profile/update/pic/', ProfilePicUpdate.as_view(),name='profile_pic_update'),
    path('profile/student/<id>', StudentProfileView.as_view(),name='student_profile_view'),
    path('scd/add/<id>', AddStudentCourseData.as_view(),name='add_scd'),
    path('scd/delete/<id>', RemoveSCD.as_view(),name='delete_scd'),

    #trainer
    path('trainer/home/', TrainerDashboard.as_view(),name='trainer_dashboard'),
    path('trainer_registration/', TrainerRegistrationView.as_view(),name='trainer_registration'),
    path('trainer/students/', MyStudents.as_view(),name='my_students'),
    path('trainer/upcoming_batches/', UpcomingBatchView.as_view(),name='upcoming_batches'),
    path('trainer/active_batches/', ActiveBatchView.as_view(),name='active_batches'),
    path('trainer/view_queries/', ViewQueries.as_view(),name='view_queries'),
    path('trainer/view_query/<id>', DetailedViewQuery.as_view(),name='view_query'),
    path('trainer/batch_active_list/', ActiveBatchList.as_view(),name='active_batch_list'),
    path('trainer/batch_content/<id>', BatchContent.as_view(),name='batch_content'),
    path('trainer/batch_content_list/<id>', BatchContentList.as_view(),name='batch_content_list'),
    path('trainer/add_assignment/', AddAssignment.as_view(),name='add_assignment'),
    path('trainer/assignment_list/',ViewAssignments.as_view(),name='assignments_listed'),
    path('trainer/assignment/submission/<id>/',ViewSubmissions.as_view(),name='submissions'),
    path('trainer/project/submissions/',ViewProjectSubmissions.as_view(),name='project_submissions'),
    path('trainer/project/submissions/update/<id>/',UpdateSPD.as_view(),name='update_spd'),
    






    #sales
    path('sales/home/', SalesDashboard.as_view(),name='sales_dashboard'),
    path('lead/create/', CreateLead.as_view(),name='create_lead'),
    path('lead/new/', MyNewLead.as_view(),name='new_lead'),
    path('lead/in_pipeline/', MyLeadInPipeline.as_view(),name='lead_in_pipeline'),
    path('lead/closed/', MyClosedLead.as_view(),name='closed_lead'),
    path('lead/register/', MyLeadRegister.as_view(),name='lead_register'),
    path('lead/update/<id>/', LeadUpdateView.as_view(),name='lead_update'),
    path('learner/create/<id>/', CreateStudentView.as_view(),name='create_student'),


    #batch operations
    path('batch_register/', AllBatchView.as_view(),name='batch_register'),
    path('active_batch_register/', AllActiveBatchView.as_view(),name='active_batch_register'),
    path('batch_creation_form/', AddBatchView.as_view(),name='batch_creation_form'),
    path('batch/edit/<id>/',EditBatchView.as_view(),name='batch_edit'),
    path('batch/delete/<id>/',DeleteBatch.as_view(),name='batch_delete'),
    path('upcoming_batch_register/', AllUpcomingBatchView.as_view(),name='upcoming_batch_register'),






    #operations
    path('operations/home/', OperationsDashboard.as_view(),name='operations_dashboard'),
    path('all_trainer_list/',TrainerList.as_view(),name='all_trainer_list'),
    path('trainer_profile/<id>/',TrainerProfileView.as_view(),name='trainer_profile'),
    path('query_list/', QueryList.as_view(),name='query_list'),
    path('reply_query/<id>/', ReplyQuery.as_view(),name='reply_query'),
    path('deactivate/staff/<id>/', DeactivateStaff.as_view(),name='deactivate_staff'),
    path('activate/staff/<id>/', ActivateStaff.as_view(),name='activate_staff'),
    path('deactivate/student/<id>/', DeactivateStudent.as_view(),name='deactivate_student'),
    path('activate/student/<id>/', ActivateStudent.as_view(),name='activate_student'),







    #admin
    path('main/home/',AdminDashboardView.as_view(),name='admin_view'),
    path('main/operations_register/',OperationsRegisterView.as_view(),name='operations_register'),
    path('main/sales_register/',SalesRegisterView.as_view(),name='sales_register'),
    path('main/trainer_register/',TrainerRegisterView.as_view(),name='trainer_register'),
    path('main/staff_registration/',RegisterNewStaff.as_view(),name='staff_registration'),
    path('main/assign_task/',AssignTask.as_view(),name='assign_task'),





    #students
    path('student/home/',StudentDashboard.as_view(),name='student_dashboard'),
    path('my_courses/',MyCourses.as_view(),name='my_courses'),
    path('my_active_courses/',MyCourseList.as_view(),name='my_active_courses'),
    path('my_video_list/<id>/',VideoList.as_view(),name='my_video_list'),
    path('videoplayer/<id>',PlayVideo.as_view(),name='videoplayer'),
    path('send_query/',SendQuery.as_view(),name='send_query'),
    path('view_query_reply/',ViewQueryReply.as_view(),name='view_query_reply'),
    path('view_reply/<id>/',ViewQReply.as_view(),name='view_reply'),
    path('send_doubt/',SendDoubt.as_view(),name='send_doubt'),
    path('view_doubt_reply/',ViewDoubtReply.as_view(),name='view_doubt_reply'),
    path('view_dreply/<id>/',ViewDReply.as_view(),name='view_dreply'),
    path('student/assignments/',ListAssignments.as_view(),name='assignment_list'),
    path('student/assignment/<id>/',ViewAssignment.as_view(),name='assignment'),
    path('student/assignment/submit/<id>/',SubmitAssignment.as_view(),name='submit_assignment'),
    path('student/available_projects/',ListProjects.as_view(),name='list_projects'),
    path('student/submit_project/<id>/',SubmitProject.as_view(),name='submit_project'),
    path('student/certificates/',GetCertificates.as_view(),name='get_certificates'),
    path('student/certificate/<id>/',GetFile.as_view(),name='see_certificate'),
]


urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.db.models import Q
from uuid import uuid4

# Create your models here.
class CertificateTemplate(models.Model):
    name = models.CharField(max_length=100,default='sample')
    certificate = models.FileField(default="Certificate.jpg", blank=True,null=True)

    def __str__(self):
        return self.name


class Staff(models.Model):
    value= (
    ('1', 'Operations'),
    ('2', 'Sales'),
    ('3', 'Trainer'),
    ('4', 'Admin'),
    )
    state = (
    ('Andhra Pradesh','Andhra Pradesh'),
    ('Arunachal Pradesh','Arunachal Pradesh'),
    ('Assam','Assam'),
    ('Bihar','Bihar'),
    ('Chhattisgarh','Chattisgarh'),
    ('Goa','Goa'),
    ('Gujarat','Gujarat'),
    ('Haryana','Haryana'),
    ('Himachal Pradesh','Himachal Pradesh'),
    ('Jharkhand','Jharkhand'),
    ('Karnataka','Karnataka'),
    ('Kerala','Kerala'),
    ('Madhya Pradesh','Madhya Pradesh'),
    ('Maharashtra','Maharashtra'),
    ('Manipur','Manipur'),
    ('Meghalaya','Meghalaya'),
    ('Mizoram','Mizoram'),
    ('Nagaland','Nagaland'),
    ('Odisha','Odisha'),
    ('Rajasthan','Rajasthan'),
    ('Sikkim','Sikkim'),
    ('Tamil Nadu','Tamil Nadu'),
    ('Telangana','Telangana'),
    ('Tripura','Tripura'),
    ('Uttar Pradesh','Uttar Pradesh'),
    ('Uttarakhand','Uttarakhand'),
    ('West Bengal','West Bengal')
    )
    groups = (
        ('AB+', 'AB+'),
        ('AB-', 'AB-'),
        ('A+', 'A+'),
        ('A-', 'A-'),
        ('B+', 'B+'),
        ('B-', 'B-'),
        ('O+', 'O+'),
        ('O-', 'O-'),
        )

    user = models.OneToOneField(User,on_delete=models.CASCADE,null=True,blank=True)
    name = models.CharField(max_length=100,null=True, blank=True)
    empid = models.CharField(max_length=100,null=True, blank=True)
    mobile = models.CharField(max_length=10,null=True, blank=True)
    email = models.EmailField(max_length=200,null=True, blank=True)
    sex = models.CharField(max_length=10,null=True,choices=(('Male','Male'),('Female','Female')), blank=True)
    dob = models.DateField(null=True, blank=True)
    doj = models.DateField(null=True, blank=True)
    blood_group = models.CharField(max_length=100,null=True, blank=True,choices=groups)
    house = models.CharField(max_length=100,null=True, blank=True)
    street =models.CharField(max_length=100,null=True, blank=True)
    street2 =models.CharField(max_length=100,null=True, blank=True)
    city = models.CharField(max_length=100,null=True, blank=True)
    state = models.CharField(max_length=100,null=True,choices=state, blank=True)
    stype = models.CharField(max_length=100,null=True,choices=value, blank=True)
    status = models.CharField(max_length=20,choices=(('Active','Active'),('Inactive','Inactive')),default='Active')
    profile_pic = models.ImageField(null=True, blank=True,default="user-circle-solid.jpg")

    def __str__(self):
        return self.name

    def is_trainer(self):
        if self.stype == 'Trainer':
            return True
        else:
            return False

class Courses(models.Model):
    name = models.CharField(max_length=300,null=True)
    fee = models.CharField(max_length=6)
    link = models.CharField(max_length=1000,null=True, blank=True)
    project_file = models.CharField(max_length=1000,null=True,blank=True)
    pic = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

class Batch(models.Model):
    mod_value= [
    ('1', 'Weekday'),
    ('2', 'Weekend')
    ]
    status_value= [
        ('Yet to start', 'Yet to start'),
        ('Ongoing', 'Ongoing'),
        ('Completed', 'Completed'),
    ]
    subject = models.ForeignKey(Courses,on_delete=models.CASCADE,null=True,blank=True)
    trainer = models.ForeignKey(Staff,on_delete=models.CASCADE,null=True,limit_choices_to={'stype':"3"},blank=True)
    timing = models.CharField(max_length=100, null=True,blank=True)
    start_date = models.DateField(null=True,blank=True)
    end_date = models.DateField(null=True,blank=True)
    link = models.CharField(max_length=1000,null=True,blank=True)
    passcode = models.CharField(max_length=100,null=True,blank=True,default="N/A")
    mode = models.CharField(max_length=100,choices=mod_value,default=1,blank=True)
    status = models.CharField(max_length=100,choices=status_value,blank=True,default="Yet to start")

    def __str__(self):
        st =" started on "
        at = " at "
        by = " by "
        return "%s %s %s %s %s %s %s" %(self.subject ,st, self.start_date ,at, self.timing,by,self.trainer)


class BatchData(models.Model):
    batch = models.ForeignKey(Batch,on_delete=models.CASCADE,null=True,blank=True)
    topic = models.CharField(max_length=100,null=True, blank=True)
    link = models.CharField(max_length=1000,null=True, blank=True)
    datecreated = models.DateField(null=True,blank=True,auto_now_add=True)

    def __str__(self):
        return "%s %s" %(self.batch , self.topic)


class Project(models.Model):
    batch = models.ForeignKey(Batch,on_delete=models.CASCADE,null=True,blank=True)
    status = models.CharField(max_length=20,choices=(('Active','Active'),('Inactive','Inactive')),default='Active',blank=True,null=True)

    def __str__(self):
        return "%s" %(self.batch)



class Assignment(models.Model):
    batch = models.ForeignKey(Batch,on_delete=models.CASCADE,null=True,blank=True,limit_choices_to={'status':"Ongoing"})
    topic = models.CharField(max_length=100,null=True, blank=True)
    description = models.TextField(max_length=100,null=True, blank=True)
    link = models.CharField(max_length=1000,null=True, blank=True)
    datecreated = models.DateTimeField(null=True,blank=True,auto_now_add=True)

    def __str__(self):
        return "%s %s" %(self.batch , self.topic)



class Task(models.Model):
    status_value= [
        ('Yet to start', 'Yet to start'),
        ('In progress', 'In progress'),
        ('Completed', 'Completed'),
    ]
    user = models.ForeignKey(Staff,on_delete=models.CASCADE,null=True)
    title = models.CharField(max_length=100,null=True)
    description = models.TextField(max_length=500,null=True)
    created_at = models.DateTimeField(auto_now_add=True,null=True,blank=True)
    assigned_by = models.ForeignKey(Staff,on_delete=models.CASCADE,null=True,related_name='sender')
    status = models.CharField(max_length=100,choices=status_value,default='Yet to start',blank=True)

    def __str__(self):
        return "%s %s" %(self.user , self.title)
    
    class Meta:
        ordering=['created_at','-status']



class Student(models.Model):
    state = (
    ('Andhra Pradesh','Andhra Pradesh'),
    ('Arunachal Pradesh','Arunachal Pradesh'),
    ('Assam','Assam'),
    ('Bihar','Bihar'),
    ('Chhattisgarh','Chattisgarh'),
    ('Goa','Goa'),
    ('Gujarat','Gujarat'),
    ('Haryana','Haryana'),
    ('Himachal Pradesh','Himachal Pradesh'),
    ('Jharkhand','Jharkhand'),
    ('Karnataka','Karnataka'),
    ('Kerala','Kerala'),
    ('Madhya Pradesh','Madhya Pradesh'),
    ('Maharashtra','Maharashtra'),
    ('Manipur','Manipur'),
    ('Meghalaya','Meghalaya'),
    ('Mizoram','Mizoram'),
    ('Nagaland','Nagaland'),
    ('Odisha','Odisha'),
    ('Rajasthan','Rajasthan'),
    ('Sikkim','Sikkim'),
    ('Tamil Nadu','Tamil Nadu'),
    ('Telangana','Telangana'),
    ('Tripura','Tripura'),
    ('Uttar Pradesh','Uttar Pradesh'),
    ('Uttarakhand','Uttarakhand'),
    ('West Bengal','West Bengal')
)

    groups = (
    ('AB+', 'AB+'),
    ('AB-', 'AB-'),
    ('A+', 'A+'),
    ('A-', 'A-'),
    ('B+', 'B+'),
    ('B-', 'B-'),
    ('O+', 'O+'),
    ('O-', 'O-'),
    )
    user= models.OneToOneField(User,on_delete=models.CASCADE,null=True,blank=True)
    name = models.CharField(max_length=100,blank=True)
    mobile = models.CharField(max_length=10,blank=True)
    email = models.EmailField(max_length=200,blank=True)
    sex = models.CharField(max_length=10,null=True,choices=(('Male','Male'),('Female','Female')),blank=True)
    dob = models.DateField(null=True, blank=True)
    blood_group = models.CharField(max_length=100,null=True, blank=True,choices=groups)
    house = models.CharField(max_length=100,null=True,blank=True)
    street =models.CharField(max_length=100,null=True,blank=True)
    street2 =models.CharField(max_length=100,null=True,blank=True)
    city = models.CharField(max_length=100,null=True,blank=True)
    state = models.CharField(max_length=100,null=True,choices=state,blank=True)
    course_enrolled = models.CharField(max_length=100,null=True,blank=True)
    now_attending = models.CharField(max_length=100,null=True,blank=True)
    start_date = models.DateField(null=True,blank=True)
    shared = models.BooleanField(default=False,choices=((True, 'Yes'), (False, 'No')),blank=True)
    payment = models.CharField(max_length=10,choices=(('Full','Full'),('Half','Half')),default='Half',blank=True)
    status = models.CharField(max_length=20,choices=(('Active','Active'),('Inactive','Inactive')),default='Active',blank=True)
    profile_pic = models.ImageField(null=True,default="student.jpg")
    total_fees = models.IntegerField(null=True,blank=True)
    fees_paid = models.IntegerField(null=True,blank=True)
    balance = models.IntegerField(null=True,blank=True)

    def __str__(self):
        return self.name


class StudentCourseData(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE,related_name='student',null=True,blank=True)
    batch = models.ForeignKey(Batch, on_delete=models.CASCADE,related_name='batch',limit_choices_to=Q(status="Ongoing")|Q(status="Yet to start"),blank=True)
    payment = models.CharField(max_length=10,choices=(('Full','Full'),('Half','Half'),('Not Paid','Not Paid')),default='Not Paid',blank=True)
    optional = models.CharField(max_length=20,choices=(('Yes','Yes'),('No','No')),default="No",null=True)
    
    def __str__(self):
        s=" 's "
        return "%s %s %s" % (self.student,s, self.batch)

accounts/templates/accounts/mini/batches.html
<div class="col-lg-6">
    <div class="content-page">
        <div class="row">
            <div class="col-md-12">
                <div class="page-title mb-2">
                    Current-Batch-List
                </div>
                <div class="table-responsive">
                    <table class="table table-striped custom-table">
                        <thead>
                            <tr>
                                <th style="min-width:91px;">Subject</th>
                                <th style="min-width:50px;">Timing</th>
                                <th style="min-width:50px;">Type</th>
                                <th style="min-width:50px;">Start Date</th>
                                <th style="min-width:50px;">End Date</th>
                                <th class="text-right">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for i in ba %}
                            <tr>
                                <td>{{i.subject}}</td>
                                <td>{{i.timing}}</td>
                                <td>{{i.get_mode_display}}</td>
                                <td>{{i.start_date}}</td>
                                <td>{{i.end_date}}</td>
                                <td class="text-right">
                                    <div class="dropdown dropdown-action">
                                        <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown"
                                            aria-expanded="false"><i class="fas fa-ellipsis-v"></i></a>
                                        <div class="dropdown-menu dropdown-menu-right">
                                            <a class="dropdown-item" href="{%url 'batch_edit' i.id %}">
                                                <i class="fas fa-pencil-alt m-r-5"></i> Edit</a>
                                            <a class="dropdown-item" href="{%url 'batch_delete' i.id %}" >
                                                <i class="fas fa-trash m-r-5"></i>Delete</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
            
                                
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

accounts/templates/accounts/mini/lead_chart.html
<div class="col-lg-6 col-md-12 col-sm-12 col-12">   
    <div class="content-page">
        <div class="page-title">Lead Status</div>
        <div id="graph"></div>
    </div>
</div>
<script>
    var colorsDash = ['#8E37D7', '#01c0c8' ,'#6B8DD6'];
    Morris.Donut({
    element: 'graph',
    colors: colorsDash,
    data: [
        {value: '{{closure_count}}', label: 'Converted'},
        {value: '{{new_lead_count}}', label: 'New'},
        {value: '{{pipeline_lead_count}}', label: 'In Pipeline'},
    ],
    formatter: function (x) { return x }
    }).on('click', function(i, row){
    console.log(i, row);
    });
</script>

accounts/templates/accounts/mini/staff_pending_task.html
<div class="col-lg-6">
    <div class="content-page">
        <div class="row">
            <div class="col-md-12">
                <div class="page-title mb-2">
                    Task List
                </div>
                <div class="table-responsive">
                    <table class="table table-striped custom-table">
                        <thead>
                            <tr>
                                <th style="min-width:px;">Staff</th>
                                <th style="min-width:px;">Dept.</th>
                                <th style="min-width:91px;">Task</th>
                                <th style="min-width:50px;">Description</th>
                                <th style="min-width:50px;">Status</th>
                                <th class="text-right">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for i in staff_pending_task %}
                            <tr>
                                <td>{{i.user}}</td>
                                <td>{{i.user.get_stype_display}}</td>
                                <td>{{i.title}}</td>
                                <td>{{i.description}}</td>
                                <td>{{i.status}}</td>
                                <td class="text-right">
                                    <div class="dropdown dropdown-action">
                                        <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown"
                                            aria-expanded="false"><i class="fas fa-ellipsis-v"></i></a>
                                        <div class="dropdown-menu dropdown-menu-right">
                                            <a class="dropdown-item" href="{% url 'task_detail' i.id %}">
                                                <i class="fa fa-eye m-r-5"></i> View</a>
                                            <a class="dropdown-item" href="{% url 'task_update' i.id %}" >
                                                <i class="fas fa-trash"></i>&nbsp;&nbsp;&nbsp;Delete</a>
                                        </div>
                                    </div>
                                </td>
                                {% empty %}
                                <td colspan="6"><center><b>No pending tasks</b></center></td>
                            </tr>
                            {% endfor %}
            
                                
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

accounts/templates/accounts/mini/student_register.html
<div class="row mt-2">
    <div class="col-lg-12">
        <div class="content-page">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                    <div class="page-title mb-2">
                        All Students
                    </div>
                    <div class="table-responsive">
                        <table class="table table-striped custom-table">
                            <thead>
                                <tr>
                                    <th style="min-width:50px;">Name </th>
                                    <th style="min-width:74px;">Email</th>
                                    <th style="min-width:50px;">Course Enrolled</th>
                                    <th style="min-width:50px;">Now Attending</th>
                                    <th style="min-width:98px;">Start Date</th>
                                    <th style="min-width:90px;">Shared</th>
                                    <th style="min-width:90px;">Payement</th>
                                    <th style="min-width:90px;">Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for student in students %}
                                {% if student.user.is_active %}
                                <tr>
                                    <td>
                                        <h2><a href="{% url 'student_profile_view' student.id %}" class="avatar text-white">
                                            <img src="{{student.profile_pic.url}}" width="40" height="40" alt="{{student.name}}">
                                        </a></h2>
                                        <h2><a href="{% url 'student_profile_view' student.id %}">{{student.name}}</a><span></span></h2>
                                    </td>
                                    <td>{{student.email}}</td>
                                    <td>{{student.course_enrolled|join:", " }}</td> 
                                    <td>{{student.now_attending|join:", " }}</td>
                                    <td>{{student.start_date}}</td>
                                    <td>{{student.get_shared_display}}</td>
                                    <td>{{student.payment}}</td>
                                    <td>{{student.status}}</td>
                                    {% if s.stype == "1" or s.stype == "4" %}
                                    <td class="text-right" style="width:10px">
                                        <div class="dropdown dropdown-action">
                                            <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown"
                                                aria-expanded="false"><i class="fas fa-ellipsis-v"></i></a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                    <a class="dropdown-item" href="{% url 'deactivate_student' student.id %}"><i
                                                        class="fas fa-ban m-r-5"></i>Deactivate</a>
                                            </div>
                                        </div>
                                    </td>
                                    {% endif %}
                                </tr>
                                {% else %}
                                <tr class="holiday-completed">
                                    <td>
                                        <h2><a href="" class="avatar text-white"><img src="{{student.profile_pic.url}}" width="40" height="40" alt="{{student.name}}"></a></h2>
                                        <h2>{{student.name}} <span></span></h2>
                                    </td>
                                    <td>{{student.email}}</td>
                                    <td>{{student.course_enrolled|join:", " }}</td>
                                    <td>{{student.now_attending|join:", " }}</td>
                                    <td>{{student.start_date}}</td>
                                    <td>{{student.get_shared_display}}</td>
                                    <td>{{student.payment}}</td>
                                    <td>{{student.status}}</td>
                                    {% if s.stype == "1" or s.stype == "4" %}
                                    <td class="text-right" style="width:10px">
                                        <div class="dropdown dropdown-action">
                                            <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown"
                                                aria-expanded="false"><i class="fas fa-ellipsis-v"></i></a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <a class="dropdown-item" href="{% url 'activate_student' student.id %}"><i
                                                    class="far fa-check-circle m-r-5"></i>Activate</a>
                                            </div>
                                        </div>
                                    </td>
                                    {% endif %}
                                </tr>
                                {% endif %}
                                    
                                {% empty %}
                                    <h3>No students in list</h3>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

accounts/templates/accounts/mini/upcoming_batch.html
<div class="col-lg-6">
    <div class="content-page">
        <div class="row">
            <div class="col-md-12">
                <div class="page-title mb-2">
                    Upcoming Batch List
                </div>
                <div class="table-responsive">
                    <table class="table table-striped custom-table">
                        <thead>
                            <tr>
                                <th style="min-width:91px;">Subject</th>
                                <th style="min-width:50px;">Timing</th>
                                <th style="min-width:50px;">Type</th>
                                <th style="min-width:50px;">Start Date</th>
                                <th style="min-width:50px;">End Date</th>
                                <th class="text-right">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for i in by %}
                            <tr>
                                <td>{{i.subject}}</td>
                                <td>{{i.timing}}</td>
                                <td>{{i.get_mode_display}}</td>
                                <td>{{i.start_date}}</td>
                                <td>{{i.end_date}}</td>
                                <td class="text-right">
                                    <div class="dropdown dropdown-action">
                                        <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown"
                                            aria-expanded="false"><i class="fas fa-ellipsis-v"></i></a>
                                        <div class="dropdown-menu dropdown-menu-right">
                                            <a class="dropdown-item" href="{%url 'batch_edit' i.id %}">
                                                <i class="fas fa-pencil-alt m-r-5"></i> Edit</a>
                                            {% if i.trainer__stype == "1" %}
                                            <a class="dropdown-item" href="{%url 'batch_delete' i.id %}" >
                                                <i class="fas fa-trash m-r-5"></i>Delete</a>
                                            {% endif %}
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
            
                                
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>